import type { Metadata } from "next";
import Link from "next/link";
import { CalendarDays, ExternalLink } from "lucide-react";
import type { ContentCategory } from "@/types";
import { CategoryTabs } from "@/components/discovery/category-tabs";
import { CategoryBadges } from "@/components/title/category-badges";
import { MediaImage } from "@/components/ui/media-image";
import { titles } from "@/lib/data/catalog";
export const metadata: Metadata = { title: "Airing Calendar", description: "See currently airing BL, GL, and Omegaverse productions by weekday." };
const weekdays = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];
export default async function AiringPage({ searchParams }: { searchParams: Promise<{ category?: ContentCategory }> }) { const { category } = await searchParams; const airing = titles.filter((title) => title.status === "airing" && (!category || title.categories.includes(category))); return <div className="page-shell standard-page"><header className="page-heading"><p className="eyebrow">This week</p><h1>Airing Calendar</h1><p>Current schedules from the local catalog. Always confirm timing with the official provider.</p></header><CategoryTabs basePath="/airing" active={category} />{weekdays.map((day) => { const items = airing.filter((title) => title.airingDay === day); if (!items.length) return null; return <section className="schedule-day" key={day}><div className="day-label"><CalendarDays /><h2>{day}</h2></div><div className="schedule-list">{items.map((title) => <article key={title.id}><Link href={`/title/${title.slug}`} className="schedule-poster"><MediaImage src={title.posterUrl} alt={`${title.title} poster`} sizes="82px" /></Link><div className="schedule-info"><CategoryBadges categories={title.categories} compact /><Link href={`/title/${title.slug}`}><h3>{title.title}</h3></Link><p>{title.country} · Episode schedule: {title.episodes ? `of ${title.episodes}` : "TBA"}</p></div>{title.watchProviders[0]?.url ? <a className="provider-link" href={title.watchProviders[0].url} target="_blank" rel="noopener noreferrer">{title.watchProviders[0].name}<ExternalLink /></a> : <span className="provider-missing">Provider TBA</span>}</article>)}</div></section>; })}{!airing.length ? <div className="empty-state"><h2>No releases are currently scheduled.</h2><p>Try another category or check upcoming titles.</p><Link className="button-primary" href="/upcoming">View upcoming</Link></div> : null}</div>; }
